# Generated by Django 3.1.2 on 2020-12-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='12', max_length=120),
            preserve_default=False,
        ),
    ]
